# Generated by Django 2.2.22 on 2024-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('dob', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
