# Generated by Django 2.2.22 on 2024-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
